baseurl = "/grim/"
languageCode = "en-gb"
title = "Bootstrapping a Secure Infrastructure"
publishDir = "../docs"

[params]
	# General information
	author = "Oliver Mussell"
	description = "Bootstrapping a Secure Infrastructure"

#	# Repository
#	provider = "GitHub"
#	repo_url = "https://github.com/omussell/homelab"

	#version = "1.0.0"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"
#
#	permalink = "#"
#
#	# Custom assets
#	custom_css = []
#	custom_js  = []
#
#	# Syntax highlighting theme
#	highlight_css  = ""

[params.palette]
    	primary = "grey"
    	accent  = "dark purple"

[params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[[menu.main]]
	name   = "Overview"
	url    = "overview/"
	weight = 10

[[menu.main]]
	name   = "Design"
	url    = "design/"
	weight = 20

[[menu.main]]
	name   = "Implementation"
	url    = "implementation/"
	weight = 30

[[menu.main]]
	name   = "Homelab"
	url    = "test/"
	weight = 40

[blackfriday]
	smartypants    = true
	fractions      = true
	smartDashes    = true
	plainIDAnchors = true
