site_name: "GRIM"
theme:
  name: "material"
  font: false
  palette:
    primary: grey
    accent: blue
  icon:
    logo: material/weather-lightning
  favicon: images/weather-lightning.svg
  features:
    - navigation.instant

nav:
    - Home: index.md
    - Design: design.md
    - GRIM: grim.md

markdown_extensions:
  - toc:
      permalink: True
