site_name: "GRIM"
theme:
  name: "material"

docs_dir: 'mkdocs'
site_dir: 'docs'

nav:
  - Overview: index.md
  - Design: design.md
  - Implementation: implementation.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: True
